config/routes.rb
Rails.application.routes.draw do
  root to: 'learns#index'
  
  resources :learns,except: [:show]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learn.rb
class Learn < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :studydate, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :learns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :require_user_logged_in
   
  def index
    @learns = current_user.learns.all
  end
  
  def new
    @learn = current_user.learns.build
  end
  
  def create
    @learn = current_user.learns.build(learn_params)

    if @learn.save
      flash[:success] = '勉強記録が正常に作成されました'
      redirect_to '/'
    else
      flash.now[:danger] = '勉強記録が作成されませんでした'
      render :new
    end
  end

  def edit
    @learn = current_user.learns.find_by(id: params[:id])
  end

  def update
    @learn = current_user.learns.find_by(id: params[:id])
    
    if @learn.update(learn_params)
      flash[:success] = '勉強記録は正常に更新されました'
      redirect_to '/'
    else
      flash.now[:danger] = '勉強記録は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @learn = current_user.learns.find_by(id: params[:id])
    @learn.destroy
    
    flash[:success] = '勉強記録は正常に削除されました'
    redirect_to learns_url
  end

  private

  # Strong Parameter
  def learn_params
    params.require(:learn).permit(:studydate, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to '/'
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Studyrecords</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '新規ユーザー登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studyrecords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/learns/edit.html.erb
<h1>勉強記録編集ページ</h1>
<div class="row">
  <div class="col-12">
    <%= form_with(model: @learn) do |f| %>
      <% if @learn.errors.any? %>
        <div id="error_explanation">
          <ul class="mb-0">
            <% @learn.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3 col-3">
        <%= f.label :studydate, '日付' %>
        <%= f.date_select :studydate, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :content, '勉強記録' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <%= f.submit '更新', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/learns/index.html.erb
<h1>勉強記録一覧</h1>

<% if @learns.any? %>
  <table class="table-sm">
    <thead>
      <tr>
        <th>日付</th>
        <th>勉強記録</th>
        <th class="text-end"></th>
        <th class="text-end"></th>
      </tr>
    </thead>
    <tbody>
      <% @learns.each do |learn| %>
        <tr>
          <td><%= learn.studydate %></td>
          <td><%= learn.content %></td>
          <td class="text-end"><%= link_to '編集', edit_learn_path(learn), class: 'btn btn-success' %></td>
          <td class="text-end"><%= link_to '削除', learn, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to '新しく勉強記録を作成する', new_learn_path, class: "btn btn-primary" %>

app/views/learns/new.html.erb
<h1>勉強記録作成ページ</h1>
<div class="row">
  <div class="col-12">
    <%= form_with(model: @learn) do |f| %>
      <% if @learn.errors.any? %>
        <div id="error_explanation">
          <ul class="mb-0">
            <% @learn.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-2 col-3">
        <%= f.label :studydate, '日付' %>
        <%= f.date_select :studydate, class: 'form-control' %>
      </div>

      <div class="mb-2">
        <%= f.label :content, '勉強記録' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '作成', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス'%>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード(確認用)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>